version: "3"

services:
  gitlab:
    image: gitlab/gitlab-ce:13.12.15-ce.0
    container_name: "gitlab"
    restart: always
    hostname: "${IP_ADDR}"
    ports:
      - "${GITLAB_PORT}:${GITLAB_PORT}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${IP_ADDR}:${GITLAB_PORT}'
        prometheus_monitoring['enable'] = false
        gitlab_rails['initial_root_password'] = '${GITLAB_ROOT_PASSWORD}'
        unicorn['worker_processes'] = 2
        sidekiq['concurrency'] = 9
        gitlab_rails['gitlab_default_projects_features_container_registry'] = false
    volumes:
      - "gitlab-config:/etc/gitlab"
      - "gitlab-logs:/var/log/gitlab"
      - "gitlab-data:/var/opt/gitlab"
    healthcheck:
      disable: false

  runner:
    image: gitlab/gitlab-runner:alpine-v15.10.0
    container_name: "gitlab-runner"
    restart: always
    environment:
      - CI_SERVER_URL=http://gitlab:${GITLAB_PORT}/
    volumes:
      - runner-config:/etc/gitlab-runner
      - ${DOCKER_SOCKET}:/var/run/docker.sock
      - ./templates:/templates

  sonarqube-db:
    image: bitnami/postgresql:15
    container_name: "sonarqube-db"
    restart: always
    volumes:
      - sonarqube-data:/bitnami/postgresql
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: ${SQ_DB_PASSWORD}
      POSTGRESQL_DATABASE: sonarqube

  sonarqube:
    image: sonarqube:8.9.7-community
    container_name: "sonarqube"
    restart: always
    depends_on:
      - sonarqube-db
    ports:
      - "${SQ_PORT}:9000"
    environment:
      SONARQUBE_JDBC_USERNAME: postgres
      SONARQUBE_JDBC_PASSWORD: ${SQ_DB_PASSWORD}
      SONARQUBE_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonarqube

  redmine-db:
    image: postgres:12
    container_name: "redmine-db"
    restart: always
    volumes:
      - redmine-db-data:/var/lib/postgresql/data
      - ./redmine.sql:/tmp/redmine.sql
    environment:
      POSTGRES_PASSWORD: ${REDMINE_DB_PASSWORD}
      POSTGRES_DB: redmine_database

  redmine:
    image: redmine:4.2.10
    container_name: "redmine"
    restart: always
    depends_on:
      - redmine-db
    ports:
      - "${REDMINE_PORT}:3000"
    volumes:
      - ./redmine-configuration.yml:/usr/src/redmine/config/configuration.yml
      - redmine-files:/usr/src/redmine/files
    environment:
      REDMINE_DB_POSTGRES: redmine-db
      REDMINE_DB_PASSWORD: ${REDMINE_DB_PASSWORD}
      REDMINE_DB_DATABASE: redmine_database
      REDMINE_SECRET_KEY_BASE: ${REDMINE_DB_PASSWORD}

  redis:
    image: redis:6.2.11
    container_name: "redis"
    restart: always
    ports:
      - "31999:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  iii-devops-lite-db:
    image: postgres:12
    container_name: "iii-devops-lite-db"
    restart: always
    ports:
      - "${III_DB_PORT}:5432"
    volumes:
      - iii-devops-lite-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${III_DB_PASSWORD}

  iii-devops-lite-api:
    image: iiiorg/devops-lite-api:0.0.7
    container_name: "iii-devops-lite-api"
    restart: on-failure
    depends_on:
      - gitlab
      - sonarqube
      - redmine
      - redis
      - iii-devops-lite-db
    ports:
      - "${III_PORT}:10009"
    volumes:
      - ./environments.json:/environments.json
      - iii-devops-lite-file:/opt/nfs
      - iii-devops-lite-log:/logs
    environment: &iii_environment
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:${III_DB_PASSWORD}@iii-devops-lite-db:5432/devopsdb
      SQLALCHEMY_TRACK_MODIFICATIONS: false
      WTF_CSRF_CHECK_DEFAULT: false
      JSON_AS_ASCII: false
      REDMINE_INTERNAL_BASE_URL: http://redmine:3000
      REDMINE_EXTERNAL_BASE_URL: ${REDMINE_URL}
      REDMINE_ADMIN_ACCOUNT: admin
      REDMINE_ADMIN_PASSWORD: ${REDMINE_DB_PASSWORD}
      GITLAB_BASE_URL: http://gitlab:${GITLAB_PORT}
      GITLAB_EXTERNAL_BASE_URL: ${GITLAB_URL}
      GITLAB_ADMIN_ACCOUNT: root
      GITLAB_ADMIN_PASSWORD: ${GITLAB_ROOT_PASSWORD}
      SONARQUBE_INTERNAL_BASE_URL: http://sonarqube:9000/api
      SONARQUBE_EXTERNAL_BASE_URL: ${SQ_URL}
      ADMIN_INIT_LOGIN: ${III_ADMIN_LOGIN}
      ADMIN_INIT_EMAIL: ${III_ADMIN_EMAIL}
      ADMIN_INIT_PASSWORD: ${III_ADMIN_PASSWORD}
      DEPLOYER_NODE_IP: ${IP_ADDR}
      REDIS_BASE_URL: redis:6379

  iii-devops-lite-api-worker:
    image: iiiorg/devops-lite-api:0.0.7
    container_name: "iii-devops-lite-api-worker"
    restart: on-failure
    depends_on:
      - redis
      - iii-devops-lite-api
    command: celery -A apis.api:celery worker -P eventlet --loglevel=INFO
    volumes:
      - ./environments.json:/environments.json
    environment: 
      <<: *iii_environment
  
  iii-devops-lite-api-beat:
    image: iiiorg/devops-lite-api:0.0.7
    container_name: "iii-devops-lite-api-beat"
    restart: on-failure
    depends_on:
      - redis
      - iii-devops-lite-api
    command: celery -A apis.api.celery beat --loglevel=INFO --schedule=/tmp/celerybeat-schedule
    environment: 
      <<: *iii_environment

  iii-devops-lite-ui:
    image: iiiorg/devops-lite-ui:0.0.7
    container_name: "iii-devops-lite-ui"
    restart: always
    depends_on:
      - iii-devops-lite-api
    ports:
      - "80:80"
    environment:
      API_URL: http://iii-devops-lite-api:10009/

volumes:
  gitlab-data:
    driver: local
  gitlab-config:
    driver: local
  gitlab-logs:
    driver: local
  runner-config:
    driver: local

  sonarqube-data:
    driver: local

  redmine-db-data:
    driver: local
  redmine-files:
    driver: local

  iii-devops-lite-db-data:
    driver: local
  iii-devops-lite-file:
    driver: local
  iii-devops-lite-log:
    driver: local
