version: "3"

services:
  gitlab:
    image: gitlab/gitlab-ce:13.12.15-ce.0
    container_name: "gitlab"
    restart: always
    hostname: "${IP_ADDR}"
    ports:
      - "${GITLAB_PORT}:${GITLAB_PORT}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${IP_ADDR}:${GITLAB_PORT}'
        prometheus_monitoring['enable'] = false
        gitlab_rails['initial_root_password'] = '${GITLAB_ROOT_PASSWORD}'
        unicorn['worker_processes'] = 2
        sidekiq['concurrency'] = 9
        gitlab_rails['gitlab_default_projects_features_container_registry'] = false
    volumes:
      - "gitlab-config:/etc/gitlab"
      - "gitlab-logs:/var/log/gitlab"
      - "gitlab-data:/var/opt/gitlab"

  runner:
    image: gitlab/gitlab-runner:latest
    container_name: "gitlab-runner"
    restart: always
    environment:
      - CI_SERVER_URL=http://gitlab:${GITLAB_PORT}/
    volumes:
      - runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

  sq-database:
    image: docker.io/bitnami/postgresql:15
    container_name: "sonarqube-database"
    volumes:
      - sonarqube-data:/bitnami/postgresql
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: ${SQ_DB_PASSWORD}
      POSTGRESQL_DATABASE: sonarqube

  sonarqube:
    image: sonarqube:8.9.6-community
    container_name: "sonarqube"
    restart: always
    depends_on:
      - sq-database
    ports:
      - "${SQ_PORT}:9000"
    environment:
      SONARQUBE_JDBC_USERNAME: postgres
      SONARQUBE_JDBC_PASSWORD: ${SQ_DB_PASSWORD}
      SONARQUBE_JDBC_URL: jdbc:postgresql://sq-database:5432/sonarqube

  rm-database:
    image: postgres:12
    container_name: "redmine-database"
    volumes:
      - redmine-db-data:/var/lib/postgresql/data
      - ./redmine.sql:/tmp/redmine.sql
      - ./redmine.sql.log:/tmp/redmine.sql.log
    environment:
      POSTGRES_PASSWORD: ${REDMINE_DB_PASSWORD}
      POSTGRES_DB: redmine_database

  redmine:
    container_name: "redmine"
    image: redmine:4.1.5
    depends_on:
      - rm-database
    restart: always
    ports:
      - "${REDMINE_PORT}:3000"
    volumes:
      - ./redmine-configuration.yml:/usr/src/redmine/config/configuration.yml
      - redmine-files:/usr/src/redmine/files
    environment:
      REDMINE_DB_POSTGRES: rm-database
      REDMINE_DB_PASSWORD: ${REDMINE_DB_PASSWORD}
      REDMINE_DB_DATABASE: redmine_database
      REDMINE_SECRET_KEY_BASE: ${REDMINE_DB_PASSWORD}

  iii:
    build:
      context: ./devops-api/
      dockerfile: Dockerfile
    ports:
      - "${III_PORT}:10009"
    restart: on-failure
    volumes:
      - ./environments.json:/usr/src/app/environments.json
      - iii-log:/usr/src/app/logs
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:${III_DB_PASSWORD}@iii-database:5432/devopsdb
      SQLALCHEMY_TRACK_MODIFICATIONS: false
      WTF_CSRF_CHECK_DEFAULT: false
      JSON_AS_ASCII: false
      REDMINE_INTERNAL_BASE_URL: http://redmine:3000
      REDMINE_EXTERNAL_BASE_URL: http://${IP_ADDR}:${REDMINE_PORT}
      REDMINE_ADMIN_ACCOUNT: admin
      REDMINE_ADMIN_PASSWORD: ${REDMINE_DB_PASSWORD}
      GITLAB_BASE_URL: http://gitlab:${GITLAB_PORT}
      GITLAB_ADMIN_ACCOUNT: root
      GITLAB_ADMIN_PASSWORD: ${GITLAB_ROOT_PASSWORD}
      SONARQUBE_INTERNAL_BASE_URL: http://sonarqube:9000/api
      SONARQUBE_EXTERNAL_BASE_URL: http://${IP_ADDR}:${SQ_PORT}
      ADMIN_INIT_LOGIN: ${III_ADMIN_LOGIN}
      ADMIN_INIT_EMAIL: ${III_ADMIN_EMAIL}
      ADMIN_INIT_PASSWORD: ${III_ADMIN_PASSWORD}
      DEPLOYER_NODE_IP: ${IP_ADDR}
      REDIS_BASE_URL: redis:6379

  iii-database:
    image: postgres:12
    container_name: "iii-database"
    ports:
      - "${III_DB_PORT}:5432"
    volumes:
      - iii-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${III_DB_PASSWORD}
      # POSTGRES_DB: devopsdb

  redis:
    image: redis:6.2.6
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf


volumes:
  gitlab-data:
    driver: local
  gitlab-config:
    driver: local
  gitlab-logs:
    driver: local

  runner-config:
    driver: local

  sonarqube-data:
    driver: local

  redmine-db-data:
    driver: local

  redmine-files:
    driver: local

  iii-log:
    driver: local

  iii-db-data:
    driver: local