# !!! DO NOT USE THIS FILE DIRECTLY !!!
# This file is used by iiidevops-cli to generate docker-compose.yaml
# Please only run docker-compose.yaml

version: "3"

services:
  backend-base:
    image: iiiorg/devops-lite-api:0.1.3
    restart: always
    volumes:
      - ./HEAD.env:/usr/src/app/env/HEAD.env
      - ${DOCKER_SOCKET}:/var/run/docker.sock
    # We don't share depends_on with other services, because it's docker limit
    environment:
      SQLALCHEMY_HOST: iii-devops-lite-db:5432
      SQLALCHEMY_ACCOUNT: postgres
      SQLALCHEMY_PASSWORD: ${III_DB_PASSWORD}
      SQLALCHEMY_DATABASE: devopsdb
      SQLALCHEMY_TRACK_MODIFICATIONS: false
      WTF_CSRF_CHECK_DEFAULT: false
      JSON_AS_ASCII: false
      REDMINE_INTERNAL_BASE_URL: http://redmine:3000
      REDMINE_EXTERNAL_BASE_URL: ${REDMINE_URL}
      REDMINE_ADMIN_ACCOUNT: admin
      REDMINE_ADMIN_PASSWORD: ${REDMINE_DB_PASSWORD}
      GITLAB_BASE_URL: http://gitlab:${GITLAB_PORT}
      GITLAB_EXTERNAL_BASE_URL: ${GITLAB_URL}
      GITLAB_ADMIN_ACCOUNT: root
      GITLAB_ADMIN_PASSWORD: ${GITLAB_ROOT_PASSWORD}
      SONARQUBE_INTERNAL_BASE_URL: http://sonarqube:9000/api
      SONARQUBE_EXTERNAL_BASE_URL: ${SQ_URL}
      ADMIN_INIT_LOGIN: ${III_ADMIN_LOGIN}
      ADMIN_INIT_EMAIL: ${III_ADMIN_EMAIL}
      ADMIN_INIT_PASSWORD: ${III_ADMIN_PASSWORD}
      DEPLOYER_NODE_IP: ${IP_ADDR}
      REDIS_BASE_URL: redis:6379
