version: '3'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:13.12.15-ce.0'
    restart: always
    hostname: '${IP_ADDR}'
    ports:
      - '32080:80'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${IP_ADDR}'
        prometheus_monitoring['enable'] = false
        gitlab_rails['initial_root_password'] = '${DEFAULT_PASSWORD}'
        unicorn['worker_processes'] = 2
        sidekiq['concurrency'] = 9
        gitlab_rails['gitlab_default_projects_features_container_registry'] = false
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'

  runner:
    image: gitlab/gitlab-runner:latest
    container_name: "gitlab-runner"
    restart: always
    environment:
      - CI_SERVER_URL=http://gitlab:32080/
    extra_hosts:
      - "gitlab:${IP_ADDR}"
    volumes:
      - runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

  sq-database:
    image: docker.io/bitnami/postgresql:15
    volumes:
      - sonarqube-data:/bitnami/postgresql
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_DATABASE: sonarqube

  sonarqube:
    image: 'sonarqube:8.9.6-community'
    restart: always
    depends_on:
      - sq-database
    ports:
      - '31910:9000'
    environment:
      SONARQUBE_JDBC_USERNAME: postgres
      SONARQUBE_JDBC_PASSWORD: ${DB_PASSWORD}
      SONARQUBE_JDBC_URL: jdbc:postgresql://sq-database:5432/sonarqube

volumes:
  gitlab-data:
    driver: local
  gitlab-config:
    driver: local
  gitlab-logs:
    driver: local

  runner-config:
    driver: local

  sonarqube-data:
    driver: local
