"""update exlacidraw history table

Revision ID: 1080e4c00331
Revises: 9cba7afff76b
Create Date: 2022-09-29 08:49:38.342191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1080e4c00331'
down_revision = '9cba7afff76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excalidraw_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('excalidraw_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['excalidraw_id'], ['excalidraw.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('excalidraw_history')
    # ### end Alembic commands ###
