"""add Pict

Revision ID: 457ca5aab118
Revises: 1080e4c00331
Create Date: 2022-10-26 14:58:43.844858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457ca5aab118'
down_revision = '1080e4c00331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('commit_id', sa.String(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sideex_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sideex_id'], ['sideex.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pict')
    # ### end Alembic commands ###
