"""add_run_num_in_PipelineExecution

Revision ID: 4861747b578a
Revises: f9a5f67141be
Create Date: 2023-01-10 10:45:59.629146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4861747b578a'
down_revision = 'f9a5f67141be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_execution', sa.Column('run_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_execution', 'run_num')
    # ### end Alembic commands ###
