"""add_column_on_pict

Revision ID: 57977cc66b66
Revises: 457ca5aab118
Create Date: 2022-10-27 10:44:51.072995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57977cc66b66'
down_revision = '457ca5aab118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pict', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key('pict_project_id_fkey', 'pict', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pict_project_id_fkey', 'pict', type_='foreignkey')
    op.drop_column('pict', 'project_id')
    # ### end Alembic commands ###
