"""update_PipelineExecution

Revision ID: f9a5f67141be
Revises: c32d432b88c4
Create Date: 2023-01-09 18:40:13.699290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9a5f67141be'
down_revision = 'c32d432b88c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_execution', sa.Column('del_branch', sa.String(), nullable=True))
    op.drop_column('pipeline_execution', 'run_branches')
    op.drop_column('pipeline_execution', 'delete_branches')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_execution', sa.Column('delete_branches', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('pipeline_execution', sa.Column('run_branches', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('pipeline_execution', 'del_branch')
    # ### end Alembic commands ###
