stages:
- initial-pipeline
- sonarqube
.common_except:
  variables: &id001
  - $CI_COMMIT_MESSAGE =~ /.*\(store\)$/
Integration--initial pipeline:
  stage: initial-pipeline
  before_script:
  - apk add --update curl && rm -rf /var/cache/apk/*
  script:
  - curl --location -s --request POST "${API_ORIGIN}/project/issues_commit_by_name"
    --form 'project_name="'"$CI_PROJECT_NAME"'"'
  allow_failure: true
  except:
    variables: *id001
Test--SonarQube source code scan:
  stage: sonarqube
  image:
    name: iiiorg/sonarqube-runner:1.1.0
    entrypoint:
    - ''
  variables:
    iiidevops: sonarqube
    SONAR_USER_HOME: ${CI_PROJECT_DIR}/.sonar
    GIT_DEPTH: '0'
  cache:
    key: ${CI_JOB_NAME}
    paths:
    - .sonar/cache
  before_script:
    - echo "Prepare SonarQube properties file..."
    - |-
      config="sonar.host.url=$SONAR_HOST_URL
      sonar.projectKey=$CI_PROJECT_NAME
      sonar.projectName=$CI_PROJECT_NAME
      sonar.projectVersion=$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
      sonar.log.level=DEBUG
      sonar.qualitygate.wait=true
      sonar.qualitygate.timeout=600
      sonar.scm.disabled=true
      sonar.login=$SONAR_TOKEN

      sonar.scm.disabled=true
      sonar.sourceEncoding=UTF-8"
    - echo "$config" > sonar-project.properties
  script:
  - chmod a+x ./iiidevops/sonarqube/*
  - ./iiidevops/sonarqube/SonarScan
  allow_failure: true
  only:
  - master
  - Modification
  except:
    variables: *id001
