# THIS FILE IS EXTENDS BY docker-compose.${MODE}.yaml
x-logging:
  service: &default-logging
    logging:
      options:
        max-size: "10m"
        max-file: "3"

services:
  traefik:
    image: "traefik:v2.10"
    restart: always
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--providers.file.filename=/etc/traefik/dynamic.yaml"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "${DOCKER_SOCKET}:/var/run/docker.sock:ro"
      - "./ca:/ca:ro"
      - "./dynamic.yaml:/etc/traefik/dynamic.yaml:ro"

  api-base:
    image: iiiorg/devops-fastapi:ce-1.1.0
    restart: always
    volumes:
      - ${III_ENV}:/usr/src/app/env/.env
      - ${DOCKER_SOCKET}:/var/run/docker.sock:ro
    # We don't share depends_on with other services, because it's docker limit
    environment:
      DATABASE__DATABASE: develop-ce
      DATABASE__PORT: 5432
      DATABASE__PASSWORD: ${III_DB_PASSWORD}
      DATABASE__SERVER: iii-devops-lite-db
      DATABASE__USER: postgres
      EMAIL_FROM_EMAIL: ""
      EMAIL_FROM_NAME: ""
      EMAIL_SMTP_HOST: ""
      EMAIL_SMTP_PASSWORD: ""
      EMAIL_SMTP_PORT: "587"
      EMAIL_SMTP_TLS: "true"
      EMAIL_SMTP_USER: ""
      FORWARDED_ALLOW_IPS: "172.18.0.0/16"
      GITLAB__ADMIN__PASSWORD: ${GITLAB_ROOT_PASSWORD}
      GITLAB__ADMIN__USERNAME: root
      GITLAB__ENABLED: "true"
      GITLAB__INIT_TOKEN: ${GITLAB_INIT_TOKEN}
      GITLAB__URL: ${GITLAB_URL}
      INIT__FIRSTNAME: admin
      INIT__LASTNAME: 初始管理者
      INIT__USERNAME: ${III_ADMIN_LOGIN}
      INIT__EMAIL: ${III_ADMIN_EMAIL}
      INIT__PASSWORD: ${III_ADMIN_PASSWORD}
      LOG__LEVEL: DEBUG
      PLUGINS__ENABLED: "true"
      PROJECT__CORS_ORIGINS: '["http://${IP_ADDR}", "http://${IP_ADDR}:10009", "https://admin.socket.io"]'
      PROJECT__ENVIRONMENT: development
      PROJECT__FRONTEND_URL: http://${IP_ADDR}
      PROJECT__SECRET_KEY: ${III_SECRET_KEY}
      PROJECT__TITLE: DevOps API
      PROJECT__TYPE: CE
      REDIS__HOST: redis
      REDIS__PASSWORD: ${III_REDIS_PASSWORD}
      REDIS__PORT: 6379
      SENTRY__ENABLED: "true"
      SENTRY__SENTRY_DSN: https://c612982c1f917bfc982682d4ba5f8f16@sentry.iiidevops.org/14
      SONARQUBE__TOKEN: ${SONARQUBE_ADMIN_TOKEN}
      SONARQUBE__URL: ${SQ_URL}
      WEBSOCKET__ADMIN: "false"
      WEBSOCKET__PASSWORD: password
      WEBSOCKET__USERNAME: admin

  gitlab:
    <<: *default-logging
    image: gitlab/gitlab-ce:17.8.7-ce.0
    container_name: "gitlab"
    restart: always
    volumes:
      - "gitlab-config:/etc/gitlab"
      - "gitlab-logs:/var/log/gitlab"
      - "gitlab-data:/var/opt/gitlab"
    shm_size: '256m'
    healthcheck:
      disable: false

  runner:
    <<: *default-logging
    image: gitlab/gitlab-runner:alpine-v17.8.5
    container_name: "gitlab-runner"
    restart: always
    volumes:
      - runner-config:/etc/gitlab-runner
      - ${DOCKER_SOCKET}:/var/run/docker.sock:ro
      - ${TEMPLATES_DIR}:/templates

  sonarqube-db:
    <<: *default-logging
    image: bitnami/postgresql:15
    container_name: "sonarqube-db"
    restart: always
    volumes:
      - sonarqube-data:/bitnami/postgresql
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: ${SQ_DB_PASSWORD}
      POSTGRESQL_DATABASE: sonarqube

  sonarqube:
    <<: *default-logging
    image: sonarqube:9.9.6-community
    container_name: "sonarqube"
    restart: always
    ports:
      - "${SQ_PORT}:9000"
    environment:
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: ${SQ_DB_PASSWORD}
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonarqube

  redis:
    <<: *default-logging
    image: redis:7.4
    container_name: "redis"
    restart: always
    volumes:
      - ${REDIS_CONF}:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  minio:
    <<: *default-logging
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    container_name: "minio"
    restart: always
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server --console-address ":9001" /data

  iii-devops-lite-db:
    <<: *default-logging
    image: postgres:15
    container_name: "iii-devops-lite-db"
    restart: always
    ports:
      - "${III_DB_PORT}:5432"
    volumes:
      - iii-devops-lite-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${III_DB_PASSWORD}
      POSTGRES_DB: develop-ce

    healthcheck:
      test: [ "CMD-SHELL", "bash -c 'pg_isready -U $$POSTGRES_USER'" ]
      interval: 10s
      timeout: 5s
      retries: 5

  iii-devops-lite-api:
    <<: *default-logging
    extends:
      service: api-base
    container_name: "iii-devops-lite-api"
    restart: on-failure
    ports:
      - "${III_PORT}:8080"
    volumes:
      - ${III_ENV}:/usr/src/app/env/.env
      - ${DOCKER_SOCKET}:/var/run/docker.sock:ro
      - iii-devops-lite-log:/logs
      - iii-devops-lite-file:/code/.attachments

  iii-devops-lite-ui:
    <<: *default-logging
    image: iiiorg/devops-lite-ui:ce-1.1.0
    container_name: "iii-devops-lite-ui"
    restart: always
    environment:
      API_URL: http://iii-devops-lite-api:8080/
      API_WS_URL: http://iii-devops-lite-api:8080/
      CE_CUSTOM_TITLE: "III DevSecOps Community"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/prod-api/docs || exit 1"]
      interval: 10s
      timeout: 1s
      retries: 5

  iii-devops-lite-worker:
    <<: *default-logging
    extends:
      service: api-base
    container_name: "iii-devops-lite-worker"
    restart: always
    volumes:
      - ${DOCKER_SOCKET}:/var/run/docker.sock:ro
    command: ["/docker-entrypoint.sh", "worker"]
