# THIS FILE IS EXTENDS BY docker-compose.yaml

services:
  gitlab:
    extends:
      service: gitlab
      file: docker/docker-compose.base.yaml
    hostname: "${IP_ADDR}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${IP_ADDR}:${GITLAB_PORT}'
        prometheus_monitoring['enable'] = false
        gitlab_rails['initial_root_password'] = '${GITLAB_ROOT_PASSWORD}'
        sidekiq['concurrency'] = 9
        gitlab_rails['gitlab_default_projects_features_container_registry'] = false
    ports:
      - "${GITLAB_PORT}:${GITLAB_PORT}"

  runner:
    extends:
      service: runner
      file: docker/docker-compose.base.yaml
    environment:
      - CI_SERVER_URL=http://gitlab:${GITLAB_PORT}/
      - DOCKER_NETWORK_MODE=iiidevops-lite-network

  sonarqube-db:
    extends:
      service: sonarqube-db
      file: docker/docker-compose.base.yaml

  sonarqube:
    extends:
      service: sonarqube
      file: docker/docker-compose.base.yaml
    depends_on:
      - sonarqube-db

  redmine-db:
    extends:
      service: redmine-db
      file: docker/docker-compose.base.yaml

  redmine:
    extends:
      service: redmine
      file: docker/docker-compose.base.yaml
    depends_on:
      - redmine-db

  redis:
    extends:
      service: redis
      file: docker/docker-compose.base.yaml

  iii-devops-lite-db:
    extends:
      service: iii-devops-lite-db
      file: docker/docker-compose.base.yaml

  iii-devops-lite-api:
    extends:
      service: iii-devops-lite-api
      file: docker/docker-compose.base.yaml
    depends_on:
      gitlab:
        condition: service_started
      sonarqube:
        condition: service_started
      redmine:
        condition: service_started
      redis:
        condition: service_started
      iii-devops-lite-db:
        condition: service_healthy

  iii-devops-lite-api-worker:
    extends:
      service: iii-devops-lite-api-worker
      file: docker/docker-compose.base.yaml
    depends_on:
      - redis
      - iii-devops-lite-api

  iii-devops-lite-api-beat:
    extends:
      service: iii-devops-lite-api-beat
      file: docker/docker-compose.base.yaml
    depends_on:
      - redis
      - iii-devops-lite-api

  iii-devops-lite-ui:
    extends:
      service: iii-devops-lite-ui
      file: docker/docker-compose.base.yaml
    depends_on:
      - iii-devops-lite-api
    labels:
      - "autoheal=true"
    ports:
      - "80:80"
