include:
- project: iiidevops-templates/ci-template
  ref: master
  file: ci/template.gitlab-ci.yml
- local: iiidevops/jobs/*.yml

stages:
- initial
- scan
- build
- deploy
- test
- userjobs

Test--SonarQube source code scan:
  variables:
    iiidevops: sonarqube
    CHART_TYPE: maven
    CHART_MAVEN_TAG: 3.6.3-openjdk-17

Test--Semgrep SAST code scan:
  variables:
    iiidevops: semgrep
    SEARCH_MAX_DEPTH: 20
    SAST_EXCLUDED_PATHS: "spec, test, tests, tmp, iiidevops, **/*.md"
