upload_file_types = [
    {"MIME Type": "audio/aac", "file extension": ".aac", "id": 1, "name": None},
    {
        "MIME Type": "application/x-abiword",
        "file extension": ".abw",
        "id": 2,
        "name": None,
    },
    {
        "MIME Type": "application/x-freearc",
        "file extension": ".arc",
        "id": 3,
        "name": None,
    },
    {"MIME Type": "video/x-msvideo", "file extension": ".avi", "id": 4, "name": None},
    {
        "MIME Type": "application/vnd.amazon.ebook",
        "file extension": ".azw",
        "id": 5,
        "name": None,
    },
    {
        "MIME Type": "application/octet-stream",
        "file extension": ".bin",
        "id": 6,
        "name": None,
    },
    {"MIME Type": "image/bmp", "file extension": ".bmp", "id": 7, "name": None},
    {"MIME Type": "application/x-bzip", "file extension": ".bz", "id": 8, "name": None},
    {
        "MIME Type": "application/x-bzip2",
        "file extension": ".bz2",
        "id": 9,
        "name": None,
    },
    {
        "MIME Type": "application/x-csh",
        "file extension": ".csh",
        "id": 10,
        "name": None,
    },
    {"MIME Type": "text/css", "file extension": ".css", "id": 11, "name": None},
    {"MIME Type": "text/csv", "file extension": ".csv", "id": 12, "name": None},
    {"MIME Type": "text/xml", "file extension": ".xml", "id": 13, "name": None},
    {
        "MIME Type": "application/msword",
        "file extension": ".doc",
        "id": 14,
        "name": "MS Office",
    },
    {
        "MIME Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "file extension": ".docx",
        "id": 15,
        "name": "MS Office",
    },
    {
        "MIME Type": "application/vnd.ms-fontobject",
        "file extension": ".eot",
        "id": 16,
        "name": None,
    },
    {
        "MIME Type": "application/epub+zip",
        "file extension": ".epub",
        "id": 17,
        "name": None,
    },
    {"MIME Type": "application/gzip", "file extension": ".gz", "id": 18, "name": None},
    {"MIME Type": "image/gif", "file extension": ".gif", "id": 19, "name": "GIF"},
    {"MIME Type": "text/html", "file extension": ".html", "id": 20, "name": None},
    {
        "MIME Type": "image/vnd.microsoft.icon",
        "file extension": ".ico",
        "id": 21,
        "name": None,
    },
    {"MIME Type": "text/calendar", "file extension": ".ics", "id": 22, "name": None},
    {
        "MIME Type": "application/java-archive",
        "file extension": ".jar",
        "id": 23,
        "name": None,
    },
    {"MIME Type": "image/jpeg", "file extension": ".jpeg", "id": 24, "name": "JPG"},
    {"MIME Type": "text/javascript", "file extension": ".js", "id": 25, "name": None},
    {
        "MIME Type": "application/json",
        "file extension": ".json",
        "id": 26,
        "name": None,
    },
    {
        "MIME Type": "application/ld+json",
        "file extension": ".jsonld",
        "id": 27,
        "name": None,
    },
    {"MIME Type": "audio/midi", "file extension": ".mid", "id": 28, "name": None},
    {"MIME Type": "audio/x-midi", "file extension": ".midi", "id": 29, "name": None},
    {"MIME Type": "audio/mpeg", "file extension": ".mp3", "id": 30, "name": None},
    {"MIME Type": "video/mpeg", "file extension": ".mpeg", "id": 31, "name": None},
    {
        "MIME Type": "application/vnd.apple.installer+xml",
        "file extension": ".mpkg",
        "id": 32,
        "name": None,
    },
    {
        "MIME Type": "application/vnd.oasis.opendocument.presentation",
        "file extension": ".odp",
        "id": 33,
        "name": None,
    },
    {
        "MIME Type": "application/vnd.oasis.opendocument.spreadsheet",
        "file extension": ".ods",
        "id": 34,
        "name": None,
    },
    {
        "MIME Type": "application/vnd.oasis.opendocument.text",
        "file extension": ".odt",
        "id": 35,
        "name": None,
    },
    {"MIME Type": "audio/ogg", "file extension": ".oga", "id": 36, "name": None},
    {"MIME Type": "video/ogg", "file extension": ".ogv", "id": 37, "name": None},
    {"MIME Type": "application/ogg", "file extension": ".ogx", "id": 38, "name": None},
    {"MIME Type": "audio/opus", "file extension": ".opus", "id": 39, "name": None},
    {"MIME Type": "font/otf", "file extension": ".otf", "id": 40, "name": None},
    {"MIME Type": "image/png", "file extension": ".png", "id": 41, "name": "PNG"},
    {"MIME Type": "application/pdf", "file extension": ".pdf", "id": 42, "name": None},
    {
        "MIME Type": "application/x-httpd-php",
        "file extension": ".php",
        "id": 43,
        "name": None,
    },
    {
        "MIME Type": "application/vnd.ms-powerpoint",
        "file extension": ".ppt",
        "id": 44,
        "name": "MS Office",
    },
    {
        "MIME Type": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "file extension": ".pptx",
        "id": 45,
        "name": "MS Office",
    },
    {
        "MIME Type": "application/vnd.rar",
        "file extension": ".rar",
        "id": 46,
        "name": "RAR",
    },
    {"MIME Type": "application/rtf", "file extension": ".rtf", "id": 47, "name": None},
    {"MIME Type": "application/x-sh", "file extension": ".sh", "id": 48, "name": None},
    {"MIME Type": "image/svg+xml", "file extension": ".svg", "id": 49, "name": None},
    {
        "MIME Type": "application/x-shockwave-flash",
        "file extension": ".swf",
        "id": 50,
        "name": None,
    },
    {
        "MIME Type": "application/x-tar",
        "file extension": ".tar",
        "id": 51,
        "name": None,
    },
    {"MIME Type": "image/tiff", "file extension": ".tiff", "id": 52, "name": None},
    {"MIME Type": "video/mp2t", "file extension": ".ts", "id": 53, "name": None},
    {"MIME Type": "font/ttf", "file extension": ".ttf", "id": 54, "name": None},
    {"MIME Type": "text/plain", "file extension": ".txt", "id": 55, "name": None},
    {
        "MIME Type": "application/vnd.visio",
        "file extension": ".vsd",
        "id": 56,
        "name": None,
    },
    {"MIME Type": "audio/wav", "file extension": ".wav", "id": 57, "name": None},
    {"MIME Type": "audio/webm", "file extension": ".weba", "id": 58, "name": None},
    {"MIME Type": "video/webm", "file extension": ".webm", "id": 59, "name": None},
    {"MIME Type": "image/webp", "file extension": ".webp", "id": 60, "name": None},
    {"MIME Type": "font/woff", "file extension": ".woff", "id": 61, "name": None},
    {"MIME Type": "font/woff2", "file extension": ".woff2", "id": 62, "name": None},
    {
        "MIME Type": "application/xhtml+xml",
        "file extension": ".xhtml",
        "id": 63,
        "name": None,
    },
    {
        "MIME Type": "application/vnd.ms-excel",
        "file extension": ".xls",
        "id": 64,
        "name": None,
    },
    {
        "MIME Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "file extension": ".xlsx",
        "id": 65,
        "name": None,
    },
    {"MIME Type": "application/xml", "file extension": ".xml", "id": 66, "name": None},
    {
        "MIME Type": "application/vnd.mozilla.xul+xml",
        "file extension": ".xul",
        "id": 67,
        "name": None,
    },
    {"MIME Type": "application/zip", "file extension": ".zip", "id": 68, "name": "ZIP"},
    {"MIME Type": "multipart/x-zip", "file extension": ".zip", "id": 69, "name": "ZIP"},
    {
        "MIME Type": "application/x-compressed",
        "file extension": ".zip",
        "id": 70,
        "name": "ZIP",
    },
    {
        "MIME Type": "application/x-zip-compressed",
        "file extension": ".zip",
        "id": 71,
        "name": "ZIP",
    },
    {
        "MIME Type": "application/x-rar",
        "file extension": ".rar",
        "id": 72,
        "name": None,
    },
    {
        "MIME Type": "application/x-rar-compressed",
        "file extension": ".rar",
        "id": 73,
        "name": None,
    },
    {"MIME Type": "video/3gpp", "file extension": ".3gp", "id": 74, "name": None},
    {"MIME Type": "audio/3gpp", "file extension": ".3gp", "id": 75, "name": None},
    {"MIME Type": "video/3gpp2", "file extension": ".3g2", "id": 76, "name": None},
    {"MIME Type": "audio/3gpp2", "file extension": ".3g2", "id": 77, "name": None},
    {
        "MIME Type": "application/x-7z-compressed",
        "file extension": ".7z",
        "id": 78,
        "name": "7z",
    },
]
